# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_USER: "default-user"
      MYSQL_PASSWORD: "default-password"
      MYSQL_ROOT_PASSWORD: "default-root-password"
      MYSQL_DATABASE: "gritlands_website"
    volumes:
      - dbData:/var/lib/mysql
    restart: always
# Commented out for now, will require some set up on LIVE server
#  storage-backup:
#    build: './build/storage_backup'
#    volumes:
#      - dbData:/var/lib/backup/data

volumes:
  app:
  dbData:
